// core/adapters/gemini.js — Gemini CLI slash-command adapter.
// Maps SKILL.md → ~/.gemini/commands/weave/<name>.toml, which Gemini CLI
// surfaces as /weave:<name> (subdirectory name becomes the namespace).
//
// TOML shape (Gemini CLI custom commands):
//   description = "..."
//   prompt = '''
//     <SKILL.md body>
//     {{args}}         # user-supplied argv is injected here
//   '''
//
// The body is kept verbatim — it's a set of instructions to the model. Gemini
// has a Shell tool and will execute the bash snippets when the prompt tells it
// to. This is the same model-to-bash chain Claude Code uses.

'use strict';

const fs = require('node:fs');
const path = require('node:path');

function detect(home) {
  return fs.existsSync(path.join(home, '.gemini'));
}

function targetDir(home) {
  // Gemini CLI: ~/.gemini/commands/<namespace>/<name>.toml
  //   → /<namespace>:<name>
  // We put files directly under commands/ and use the subdir for namespace.
  return path.join(home, '.gemini', 'commands');
}

// TOML literal string cannot contain '''; fall back to basic string with escapes.
function encodePrompt(body) {
  if (!body.includes("'''")) {
    return "'''\n" + body + "\n'''";
  }
  // Basic string: escape backslash, triple-double-quote, control chars.
  const escaped = body
    .replace(/\\/g, '\\\\')
    .replace(/"""/g, '\\"\\"\\"');
  return '"""\n' + escaped + '\n"""';
}

// TOML basic string for short description (single line).
function encodeShort(value) {
  const safe = (value || '')
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, ' ')
    .trim();
  return '"' + safe + '"';
}

function render(skill) {
  // Append {{args}} at the end so invocations like
  //   /weave:run my-flow --auto
  // pass their argv through to the prompt (Gemini CLI standard behavior).
  const body = (skill.body || '').replace(/\s+$/, '') + '\n\nUser arguments: {{args}}';
  const lines = [
    '# Generated by weave install.js — do not edit by hand.',
    '# Source: skills/' + skill.name + '/SKILL.md',
    '',
    'description = ' + encodeShort(skill.description),
    'prompt = ' + encodePrompt(body),
    '',
  ];
  return {
    filename: path.join('weave', skill.name + '.toml'),
    content: lines.join('\n'),
  };
}

module.exports = {
  name: 'gemini',
  label: 'Gemini CLI',
  detect,
  targetDir,
  render,
  requiresBash: true,      // Gemini invokes its Shell tool when prompted
};
